.TH ANALYZER 1 2022-5-29 GNU

.SH NAME
ANALYZER \- Log_Analyzer

.SH SYNOPSIS
.B Log_Analyzer.log
.RB [\-Options]
.RB [\-Logfile...]

.SH DESCRIPTION
.B Log_Analyzer
A bash script which Analyzes log files
.SH OPTIONS

.IP
.B "\-f, --format"
Define custom log format

.IP
.B "\-t , --threshold"
Set a threshold for displaying

.IP
.B "\-o , --output"
Specify output format

.IP
.B "\-h , -- help"
Display this help message

.SH AUTHOR
ANALYZER was created by Omar <ioanf31@gmail.com>
